[package]
name = "pqb_codegen"
version = "0.1.0"
authors = ["Konstantin <phpconf@gmail.com>"]





[lib]
proc-macro = true


[dependencies]
syn = "0.11.11"
quote = "0.3.15"


[dev-dependencies]
pqb = {path="../pqb"}



